image: node:latest

variables:
  FIREBASE_PROJECT_DEV: consigliere-app-client

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .npm/

stages:
  - lint
  - build
  - deploy

before_script:
  - npm ci --cache .npm --prefer-offline

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build

deploy_dev:
  stage: deploy
  environment:
    name: development
    url: https://consigliere-app-client.firebaseapp.com/
  only:
    - master
  before_script:
    - npm i -g firebase-tools
  script:
    - firebase use $FIREBASE_PROJECT_DEV --token $FIREBASE_TOKEN 
    - firebase deploy --only-hosting -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN