image: node:latest

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .npm/
  - www

stages:
  - lint
  - build
  - deploy

before_script:
  - npm ci --cache .npm --prefer-offline

lint:
  stage: lint
  script:
    - npm run lint
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'   # Execute jobs when a new commit is pushed to master branch
    - if: $CI_MERGE_REQUEST_ID            # Execute jobs in merge request context

build:
  stage: build
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'   # Execute jobs when a new commit is pushed to master branch
    - if: $CI_MERGE_REQUEST_ID            # Execute jobs in merge request context

deploy_dev:
  stage: deploy
  environment:
    name: development
    url: https://mafia-consigliere-dev.web.app/
  only:
    - master
  before_script:
    - npm i -g firebase-tools
  script:
    - firebase use dev --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN

deploy_prod:
  stage: deploy
  environment:
    name: production
    url: https://mafia-consigliere.web.app/
  only:
    - /^release-.*$/
  when: manual
  before_script:
    - npm i -g firebase-tools
  script:
    - firebase use prod --token $FIREBASE_TOKEN 
    - firebase deploy --only hosting -m "Branch $CI_COMMIT_REF_NAME, User $GITLAB_USER_EMAIL | Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN