name: Firebase dev-stand deployment

on:
  pull_request:
    branches: [master]

jobs:
  build-client:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd client
          yarn install
      - name: Build client
        run: |
          cd client
          yarn build:dev
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: www
          path: client/www
  deploy-hosting:
    name: Deploy hosting
    needs: build-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: www
          path: client/www
      - name: Install firebse tools
        run: npm i -g firebase-tools
      - name: Set firebase project to dev
        run: firebase use $PROJECT_ID --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: dev
      - name: Deploy firebase hosting
        run: firebase deploy --only hosting -m "Workflow $GITHUB_WORKFLOW, action $GITHUB_ACTION" --non-interactive --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  build-server:
    name: Build server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd server
          yarn install
      - name: Build server
        run: |
          cd server
          yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: server/dist
  deploy-functions:
    name: Deploy functions
    needs: build-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: server/dist
      - name: Install firebse tools
        run: npm i -g firebase-tools
      - name: Set firebase project to dev
        run: firebase use $PROJECT_ID --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: dev
      - name: Deploy firebase functions
        run: firebase deploy --only functions -m "Workflow $GITHUB_WORKFLOW, action $GITHUB_ACTION" --non-interactive --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
